version: "3"
services:
  teamcity-server:
    image: jetbrains/teamcity-server
    ports:
      - "8112:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./log_dir:/opt/teamcity/logs
    restart: always
  teamcity-agent-1:
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=http://teamcity-server:8111
      - AGENT_NAME=agent_1
      - DOCKER_IN_DOCKER=start
    restart: always
  teamcity-agent-2:
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=http://teamcity-server:8111
      - AGENT_NAME=agent_2
      - DOCKER_IN_DOCKER=start
    restart: always
  teamcity-nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - teamcity-server    
    restart: always
  
