version: "3"
services:
  server:
    image: jetbrains/teamcity-server
    ports:
      - "8112:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./log_dir:/opt/teamcity/logs
  teamcity-agent-1:
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=agent_1
      - DOCKER_IN_DOCKER=start
  teamcity-agent-2:
    image: jetbrains/teamcity-agent
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=agent_2
      - DOCKER_IN_DOCKER=start
